{
"--aggr_edge_atr": "0",
"--aggr_vertex_feat": "0",
"--batch_size": "64",
"--dim_pooling": "0",
"--drop_out": "0.5",
"--emb_dim": "64",
"--epochs": "100000",
"--expl_type_enc": "0",
"--lr": "0.001",
"--min_lr": 0,
"--lr_schedule_patience": "20",
"--max_struct_size": "0",
"--model": "MLP",
"--num_layer": "5",
"--rings": "0",
"--tracking": "1",
"--virtual_node": "0"
}
#"result_val": 1.3167856931686401
