{
  "--exp_name": "ZINC_CIN_ZINC.yaml_tune_['./Results/ZINC_CIN_ZINC.yaml/Hyperparameters/params_0.json', './Results/ZINC_CIN_ZINC.yaml/Hyperparameters/params_1.json', './Results/ZINC_CIN_ZINC.yaml/Hyperparameters/params_2.json', './Results/ZINC_CIN_ZINC.yaml/Hyperparameters/params_3.json', './Results/ZINC_CIN_ZINC.yaml/Hyperparameters/params_4.json', './Results/ZINC_CIN_ZINC.yaml/Hyperparameters/params_5.json', './Results/ZINC_CIN_ZINC.yaml/Hyperparameters/params_6.json']",
  "--batch_size": "64",
  "--device": "0",
  "--drop_position": "lin2",
  "--drop_rate": "0.0",
  "--dump_curves": "",
  "--early_stop": "",
  "--emb_dim": "256",
  "--epochs": "100000",
  "--eval_metric": "mae",
  "--final_readout": "sum",
  "--graph_norm": "bn",
  "--indrop_rate": "0.0",
  "--init_method": "sum",
  "--lr": "0.001",
  "--lr_scheduler": "ReduceLROnPlateau",
  "--lr_scheduler_patience": "20",
  "--max_dim": "2",
  "--max_ring_size": "8",
  "--minimize": "",
  "--model": "embed_sparse_cin",
  "--nonlinearity": "relu",
  "--num_layers": "3",
  "--num_workers": "0",
  "--readout": "mean",
  "--task_type": "regression",
  "--train_eval_period": "1",
  "--use_coboundaries": "True",
  "--use_edge_features": ""
  }
#"result_val": 0.08489168435335159
