epochs: [1]
device: [0]
train_eval_period: [1]
model: ["embed_sparse_cin"]
use_coboundaries: ["True"]
indrop_rate: [0.0]
drop_rate: [0.0, 0.5]
drop_position: ["lin2"]
graph_norm: ["bn"]
nonlinearity: ["relu"]
final_readout: ["sum"]
init_method: ["sum"]
readout: ["mean"]
lr: [0.001]
lr_scheduler: ["ReduceLROnPlateau"]
lr_scheduler_patience: ["20"]
max_dim: [2]
max_ring_size: [6, 8]
batch_size: [64]
emb_dim: [32, 64, 128, 256, 300]
num_layers: [2,3,4,5]
num_workers: [0]
task_type: ["regression"]
eval_metric: ["mae"]
minimize: [""]
use_edge_features: [""]
dump_curves: [""]
early_stop: [""]