epochs: [300]
batch_size: [64]
emb_dim: [32, 64, 128, 256, 300]
drop_out: [0, 0.5]
dim_pooling: [0,1]
num_layer: [2,3,4,5]
max_struct_size: [6, 8]
aggr_edge_atr: [0,1]
aggr_vertex_feat: [0,1]
lr:  [0.001]
expl_type_enc: [1]
virtual_node: [0]
lr_schedule_patience: [20]
rings: [1]
tracking: [1]

